SET @@session.unique_checks=0;
SET @@session.foreign_key_checks=0;
SET @@session.sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `ciclistas` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `ciclistas`;

CREATE TABLE IF NOT EXISTS `EQUIPO` (
  `EQUIPO` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EQUIPO`),
  UNIQUE INDEX `NOMEQ_UNIQUE` (`EQUIPO`)
);

CREATE TABLE IF NOT EXISTS `CICLISTA` (
  `DORSAL` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `EDAD` INT NOT NULL,
  `EQUIPO_EQUIPO` INT NOT NULL,
  PRIMARY KEY (`DORSAL`, `EQUIPO_EQUIPO`),
  UNIQUE INDEX `DORSAL_UNIQUE` (`DORSAL`),
  INDEX `fk_CICLISTA_EQUIPO_idx` (`EQUIPO_EQUIPO`),
  CONSTRAINT `fk_CICLISTA_EQUIPO`
    FOREIGN KEY (`EQUIPO_EQUIPO`)
    REFERENCES `EQUIPO` (`EQUIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `ETAPA` (
  `IDETAPA` INT NOT NULL,
  `KM` INT NOT NULL,
  `SALIDA` VARCHAR(45) NOT NULL,
  `LLEGADA` VARCHAR(45) NOT NULL,
  `CICLISTA_DORSAL` INT NOT NULL,
  PRIMARY KEY (`IDETAPA`, `CICLISTA_DORSAL`),
  INDEX `fk_ETAPA_CICLISTA1_idx` (`CICLISTA_DORSAL`),
  CONSTRAINT `fk_ETAPA_CICLISTA1`
    FOREIGN KEY (`CICLISTA_DORSAL`)
    REFERENCES `CICLISTA` (`DORSAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `PUERTO` (
  `ID` INT NOT NULL,
  `ALTURA` INT NOT NULL,
  `CATEGORIA` VARCHAR(45) NOT NULL,
  `PENDIENTE` INT NOT NULL,
  `CICLISTA_DORSAL` INT NOT NULL,
  `ETAPA_IDETAPA` INT NOT NULL,
  PRIMARY KEY (`ID`, `ALTURA`, `CICLISTA_DORSAL`, `ETAPA_IDETAPA`),
  INDEX `fk_PUERTO_CICLISTA1_idx` (`CICLISTA_DORSAL`),
  INDEX `fk_PUERTO_ETAPA1_idx` (`ETAPA_IDETAPA`),
  CONSTRAINT `fk_PUERTO_CICLISTA1`
    FOREIGN KEY (`CICLISTA_DORSAL`)
    REFERENCES `CICLISTA` (`DORSAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PUERTO_ETAPA1`
    FOREIGN KEY (`ETAPA_IDETAPA`)
    REFERENCES `ETAPA` (`IDETAPA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `MAILLOT` (
  `CODIGO` INT NOT NULL,
  `TIPO` VARCHAR(45) NOT NULL,
  `COLOR` VARCHAR(45) NOT NULL,
  `PREMIO` INT NULL,
  PRIMARY KEY (`CODIGO`)
);

CREATE TABLE IF NOT EXISTS `LLEVAR` (
  `CICLISTA_DORSAL` INT NOT NULL,
  `ETAPA_IDETAPA` INT NOT NULL,
  `MAILLOT_CODIGO` INT NOT NULL,
  PRIMARY KEY (`CICLISTA_DORSAL`, `ETAPA_IDETAPA`, `MAILLOT_CODIGO`),
  INDEX `fk_LLEVAR_ETAPA1_idx` (`ETAPA_IDETAPA`),
  INDEX `fk_LLEVAR_MAILLOT1_idx` (`MAILLOT_CODIGO`),
  CONSTRAINT `fk_LLEVAR_CICLISTA1`
    FOREIGN KEY (`CICLISTA_DORSAL`)
    REFERENCES `CICLISTA` (`DORSAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LLEVAR_ETAPA1`
    FOREIGN KEY (`ETAPA_IDETAPA`)
    REFERENCES `ETAPA` (`IDETAPA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LLEVAR_MAILLOT1`
    FOREIGN KEY (`MAILLOT_CODIGO`)
    REFERENCES `MAILLOT` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

SET @@session.sql_mode = @@session.old_sql_mode;
SET @@session.foreign_key_checks = @@session.old_foreign_key_checks;
SET @@session.unique_checks = @@session.old_unique_checks;
